eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
spring:
  application:
    name: api-base
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/clouddo?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
mybatis:
  mapper-locations: mapper/**Mapper.xml
  configuration:
      map-underscore-to-camel-case: true